name:                tree-rewriter
version:             0.1.0.0
github:              "DataKinds/tree-rewriter"
license:             BSD-3-Clause
author:              "at/DataKinds"
maintainer:          ""
copyright:           "2024 at/DataKinds"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DataKinds/tree-rewriter#readme>

dependencies:
- base >= 4.7 && < 5
- text
- text-icu
- transformers
- containers
- template-haskell
- parsec
- optparse-applicative
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wincomplete-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists

default-extensions:
- OverloadedStrings
- TemplateHaskell
- QuasiQuotes
- DeriveLift

library:
  source-dirs: src

executables:
  rosin:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tree-rewriter

tests:
  rosin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tree-rewriter
